### ISSUE TITLE
How positions of nodes are preprocessed?

### ISSUE THREAD

**Issue by Yueeeeeeee** [jiayouwyhit/deepdrawing#2]
In the data.py file, functions like calc_scale are defined, I assume these are for preprocessing the positional information of graphs. But these functions are not called in the code, could you explain how the positional information is generated and processed?

**Comment by jiayouwyhit** [comment]
Yup, it is for preprocessing the position information. We have chosen to make it done in the data preprocessing to avoid messy coding in the data.py file. But we forgot to remove this function when cleaning the code. For the positional information, basically, we do the graph drawing with prior methods and record the node positions and normalize them. For more details, please refer to our paper.

**Comment by jiayouwyhit** [comment]
Done.

**Comment by Yueeeeeeee** [comment]
Thanks for the answer. In the pyg version of LSTM as I understand it,  **g1_batch**, **g1_order,** **g1_edge_order_mask_list** should respectively refer to the graph, graph ordering and if edges exist in this ordering while g2 only have it in the opposite direction, is this correct?
